version: '3.3'

services:
  client:
    image: client-prod-c
    container_name: client-prod-c
    build:
      context: ./client
    env_file:
      - ./client/.env.production
    ports:
      - "3000:3000"
    links:
      - server
    networks:
      - default

  server:
    image: server-prod-c
    container_name: server-prod-c
    env_file:
      - ./server/.production.env
    build:
      context: ./server
    ports:
      - "4000:4000"
    networks:
      - default

networks:
  default: